// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kmdihubvvsmmleswbbrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZGlodWJ2dnNtbWxlc3diYnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NzMxNjMsImV4cCI6MjA3NjI0OTE2M30.ECfidAgBtzM1hNkjqKWz941Cg3Ta0Pl4NWZMHnvTISE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);